export const sidebarText = {
  en: {
    Menu: 'MENU',
    Dashboard: 'Dashboard',
    Homepage: 'Homepage',
    SalesAnalytics: 'Sales analytics',
    Products: 'PRODUCTS',
    Goods: 'Goods',
  },
  ukr: {
    Menu: 'МЕНЮ',
    Dashboard: 'Панель',
    Homepage: 'Домашня сторінка',
    SalesAnalytics: 'Аналітика продажів',
    Products: 'ПРОДУКТИ',
    Goods: 'Товари',
  },
};

export const goodsTableText = {
  en: {
    Header: 'All goods',
    SearchPlaceholder: 'Search...',
    SortBy: 'Sort by: ',
    AddProduct: 'Add product',
    LabelOff: 'Select a file',
    LabelOn: 'File selected',
    AddGoodsFile: 'Add product file',
    SetFile: 'Select a file',
    Name: 'Name',
    Precode: 'Precode',
    Price: 'Price',
    Code: 'Code',
    PcsGood: 'Weight/By piece',
    ByPiece: 'By piece',
    Weighted: 'Weighted',
    IdSection: 'Id section',
    IdTemplate: 'Id template',
    Action: 'Action',
    View: 'View',
    Edit: 'Edit',
    Remove: 'Remove',
  },
  ukr: {
    Header: 'Усі товари',
    SearchPlaceholder: 'Пошук...',
    SortBy: 'Сортувати за: ',
    AddProduct: 'Додати товар',
    LabelOff: 'Оберіть файл',
    LabelOn: 'Файл обрано',
    AddGoodsFile: 'Додати файл продуктів',
    SetFile: 'Обрати файл',
    Name: 'Назва',
    Precode: 'Прекод',
    Price: 'Ціна',
    Code: 'Код',
    PcsGood: 'Ваговий/штучний',
    ByPiece: 'Поштучно',
    Weighted: 'Ваговий',
    IdSection: 'Id секції',
    IdTemplate: 'Id шаблону',
    Action: 'Дія',
    View: 'Переглянути',
    Edit: 'Редагувати',
    Remove: 'Видалити',
  },
};

export const productText = {
  en: {
    Name: 'Name',
    Precode: 'Precode',
    Price: 'Price',
    Code: 'Code',
    PcsGood: 'Weight/By piece',
    ByPiece: 'By piece',
    Weighted: 'Weighted',
    IdSection: 'Id section',
    IdTemplate: 'Id template',
    Barcode: 'Barcode',
    Description: 'Description',
    BeforeValidity: 'Before validity',
    Type: 'Type',
    Image: 'Image',
    Weight: 'Weight',
    TaraWeight: 'TaraWeight',
    Submit: 'Submit',
    Reset: 'Reset',
  },
  ukr: {
    Name: 'Назва',
    Precode: 'Прекод',
    Price: 'Ціна',
    Code: 'Код',
    PcsGood: 'Ваговий/штучний',
    ByPiece: 'Поштучно',
    Weighted: 'Ваговий',
    IdSection: 'Id секції',
    IdTemplate: 'Id шаблону',
    Barcode: 'Баркод',
    Description: 'Опис',
    BeforeValidity: 'До валідації',
    Type: 'Тип',
    Image: 'Зображення',
    Weight: 'Вага',
    TaraWeight: 'Вага тари',
    Submit: 'Відправити',
    Reset: 'Скинути',
  },
};

export const toastText = {
  en: {
    AddProduct: 'Product successfully added!',
    AddProductError: 'Failed to add product!',
    EditProduct: 'Product successfully edited!',
    EditProductError: 'Failed to edit product!',
    DeleteProduct: 'Product successfully deleted!',
    DeleteProductError: 'Failed to delete product!',
    AddGoodsFile:
      'The product file has been added successfully! Please refresh the page!',
  },
  ukr: {
    AddProduct: 'Товар успішно доданий!',
    AddProductError: 'Товар не було додано!',
    EditProduct: 'Дані про товар успішно змінено!',
    EditProductError: 'Помилка оновлення даних товару!',
    DeleteProduct: 'Товар видалено успішно!!',
    DeleteProductError: 'Помилка видалення товару!',
    AddGoodsFile:
      'Файл товарів успішно доданий! Оновіть, будь ласка, сторінку!',
  },
};

export const notFoundText = {
  en: {
    NotFoundMessage: 'Sorry, the page you are looking for does not exist.',
    RedirectMessage: 'You will be redirected to the Homepage in 5 seconds.',
  },
  ukr: {
    NotFoundMessage:
      'Вибачте, сторінку на яку ви намагаєтесь перейти не існує.',
    RedirectMessage:
      'Ви будете перенаправлені на домашню сторінку через 5 секунд',
  },
};
